apiVersion: 1

datasources:
  - id: 1
    uid: T7m3_eTnk
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: >-
      http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations: []
      httpMethod: POST
    readOnly: false
  - id: 2
    uid: VNn0QQz4k
    orgId: 1
    name: Loki
    type: loki
    typeLogoUrl: ''
    access: proxy
    url: 'http://loki.logging.svc.cluster.local:3100/'
    password: ''
    user: ''
    database: ''
    basicAuth: false
    basicAuthUser: ''
    basicAuthPassword: ''
    withCredentials: false
    isDefault: false
    jsonData: {}
    secureJsonFields: {}
    version: 2
    readOnly: false
