apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: sb-drupal
spec:
  sources:
  - image: index.docker.io/paketobuildpacks/ca-certificates:3.6.3
  - image: index.docker.io/paketobuildpacks/php-dist:2.1.8
  - image: index.docker.io/paketobuildpacks/composer:0.5.15
  - image: registry.gitlab.com/shapeblock-buildpacks/composer-install:0.0.1
  - image: index.docker.io/paketobuildpacks/nginx:0.15.3
  - image: index.docker.io/paketobuildpacks/php-fpm:0.2.15
  - image: registry.gitlab.com/shapeblock-buildpacks/php-nginx:0.0.1
  - image: index.docker.io/paketobuildpacks/php-start:0.4.15
  - image: index.docker.io/paketobuildpacks/nodejs:1.7.0
  - image: index.docker.io/paketobuildpacks/procfile:5.6.4
  - image: ghcr.io/fagiani/buildpacks/fagiani_apt:0.2.5
